# Generated by Django 3.2.12 on 2022-03-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('display_photo', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('your_email', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=64)),
                ('vaccination_status', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('count_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
