# Generated by Django 3.2.12 on 2022-04-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
